apiVersion: batch/v1
kind: Job
metadata:
  name: random-hash
spec:
  completions: 5
  parallelism: 2
  template:
    metadata:
      name: random-hash
    spec:
      containers:
      - name: random-hash
        image: bash
        command: ["/bin/sh", "-c", "echo $RANDOM | base64 | head -c 20"]
      restartPolicy: Never

